from flask import Flask, send_from_directory, request, jsonify
import os

# Path to the built frontend (generated by Vite)
FRONTEND_DIST = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'frontend', 'dist')

app = Flask(__name__, static_folder=FRONTEND_DIST, static_url_path='')


@app.route('/api/chat', methods=['POST'])
def chat() -> 'flask.Response':
    """Simple chat endpoint returning a fake response."""
    data = request.get_json(force=True)
    message = data.get('message', '')
    if not message:
        return jsonify({'error': 'Missing message'}), 400
    return jsonify({'reply': f'You said: {message}'})


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve_frontend(path: str):
    """Serve the frontend app and its static assets."""
    target = os.path.join(app.static_folder, path)
    if path and os.path.exists(target):
        return send_from_directory(app.static_folder, path)
    return send_from_directory(app.static_folder, 'index.html')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
